// Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/amazon-ecs-cni-plugins/pkg/cniipamwrapper (interfaces: IPAM)

// Package mock_cniipamwrapper is a generated GoMock package.
package mock_cniipamwrapper

import (
	reflect "reflect"

	types "github.com/containernetworking/cni/pkg/types"
	current "github.com/containernetworking/cni/pkg/types/current"
	gomock "github.com/golang/mock/gomock"
)

// MockIPAM is a mock of IPAM interface
type MockIPAM struct {
	ctrl     *gomock.Controller
	recorder *MockIPAMMockRecorder
}

// MockIPAMMockRecorder is the mock recorder for MockIPAM
type MockIPAMMockRecorder struct {
	mock *MockIPAM
}

// NewMockIPAM creates a new mock instance
func NewMockIPAM(ctrl *gomock.Controller) *MockIPAM {
	mock := &MockIPAM{ctrl: ctrl}
	mock.recorder = &MockIPAMMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIPAM) EXPECT() *MockIPAMMockRecorder {
	return m.recorder
}

// ConfigureIface mocks base method
func (m *MockIPAM) ConfigureIface(arg0 string, arg1 *current.Result) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfigureIface", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfigureIface indicates an expected call of ConfigureIface
func (mr *MockIPAMMockRecorder) ConfigureIface(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigureIface", reflect.TypeOf((*MockIPAM)(nil).ConfigureIface), arg0, arg1)
}

// ExecAdd mocks base method
func (m *MockIPAM) ExecAdd(arg0 string, arg1 []byte) (types.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecAdd", arg0, arg1)
	ret0, _ := ret[0].(types.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecAdd indicates an expected call of ExecAdd
func (mr *MockIPAMMockRecorder) ExecAdd(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecAdd", reflect.TypeOf((*MockIPAM)(nil).ExecAdd), arg0, arg1)
}

// ExecDel mocks base method
func (m *MockIPAM) ExecDel(arg0 string, arg1 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecDel", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecDel indicates an expected call of ExecDel
func (mr *MockIPAMMockRecorder) ExecDel(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecDel", reflect.TypeOf((*MockIPAM)(nil).ExecDel), arg0, arg1)
}
