// Copyright 2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/aws/amazon-ecs-cni-plugins/plugins/eni/engine (interfaces: Engine)

package mock_engine

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Engine interface
type MockEngine struct {
	ctrl     *gomock.Controller
	recorder *_MockEngineRecorder
}

// Recorder for MockEngine (not exported)
type _MockEngineRecorder struct {
	mock *MockEngine
}

func NewMockEngine(ctrl *gomock.Controller) *MockEngine {
	mock := &MockEngine{ctrl: ctrl}
	mock.recorder = &_MockEngineRecorder{mock}
	return mock
}

func (_m *MockEngine) EXPECT() *_MockEngineRecorder {
	return _m.recorder
}

func (_m *MockEngine) DoesMACAddressMapToIPV4Address(_param0 string, _param1 string) (bool, error) {
	ret := _m.ctrl.Call(_m, "DoesMACAddressMapToIPV4Address", _param0, _param1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockEngineRecorder) DoesMACAddressMapToIPV4Address(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DoesMACAddressMapToIPV4Address", arg0, arg1)
}

func (_m *MockEngine) GetAllMACAddresses() ([]string, error) {
	ret := _m.ctrl.Call(_m, "GetAllMACAddresses")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockEngineRecorder) GetAllMACAddresses() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetAllMACAddresses")
}

func (_m *MockEngine) GetIPV4GatewayNetmask(_param0 string) (string, string, error) {
	ret := _m.ctrl.Call(_m, "GetIPV4GatewayNetmask", _param0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

func (_mr *_MockEngineRecorder) GetIPV4GatewayNetmask(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetIPV4GatewayNetmask", arg0)
}

func (_m *MockEngine) GetInterfaceDeviceName(_param0 string) (string, error) {
	ret := _m.ctrl.Call(_m, "GetInterfaceDeviceName", _param0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockEngineRecorder) GetInterfaceDeviceName(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetInterfaceDeviceName", arg0)
}

func (_m *MockEngine) GetMACAddressOfENI(_param0 []string, _param1 string) (string, error) {
	ret := _m.ctrl.Call(_m, "GetMACAddressOfENI", _param0, _param1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockEngineRecorder) GetMACAddressOfENI(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetMACAddressOfENI", arg0, arg1)
}

func (_m *MockEngine) IsDHClientInPath() bool {
	ret := _m.ctrl.Call(_m, "IsDHClientInPath")
	ret0, _ := ret[0].(bool)
	return ret0
}

func (_mr *_MockEngineRecorder) IsDHClientInPath() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "IsDHClientInPath")
}

func (_m *MockEngine) SetupContainerNamespace(_param0 string, _param1 string, _param2 string, _param3 string) error {
	ret := _m.ctrl.Call(_m, "SetupContainerNamespace", _param0, _param1, _param2, _param3)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockEngineRecorder) SetupContainerNamespace(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetupContainerNamespace", arg0, arg1, arg2, arg3)
}

func (_m *MockEngine) TeardownContainerNamespace(_param0 string, _param1 string) error {
	ret := _m.ctrl.Call(_m, "TeardownContainerNamespace", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockEngineRecorder) TeardownContainerNamespace(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "TeardownContainerNamespace", arg0, arg1)
}
