name: Unit Tests

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - name: Check out code
        uses: actions/checkout@v3
        with:
          path: go/src/github.com/aws/amazon-ecs-cni-plugins

      - name: Debug
        run: |
          pwd
          echo ${HOME}
          echo ${GITHUB_WORKSPACE}
          echo ${GOPATH}
          echo ${GOROOT}

      - name: Run check
        run: |
          export GOPATH=$GITHUB_WORKSPACE
          export GO111MODULE=auto
          make unit-test
